services:
  ledfx:
    image: ledfx/ledfx:latest
    container_name: ledfx
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/ledfx-config:/config
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd:/dev/snd
